### ISSUE TITLE
Outstanding Debug TODOs

### ISSUE THREAD

**Issue by mwachs5** [freechipsproject/rocket-chip#642]
Just tracking some things that remained after merging debug v13 (since they were listed on the PR before)

- [x] There should be a mapping between HARTID and DMCONTROL.hartsel. Right now it is assumed 1:1. (Covered by #650 )
- [x]  AccessRegisterCommand.transfer bit is ignored as OpenOCD is not currently setting it. (covered by #675 )
- [ ]  debugInterrupt is in DCSR but no longer in the spec
- [X] Export top level signals (covered by #639)
- [X] Need to implement the resumedready resumedall recently added to the spec (covered by #662)
- [x] Should rip out preexec support as it greatly simplifies the HW (covered by #675)
- [x] Make DATA and PROGBUF not writable while busy (demonstrated to be necessary in Spike). Fixed in #708
